#!/usr/bin/env bash

# there HAS to be an easier way to do this
dotnet add package Bullseye
dotnet add package SimpleExec
dotnet add package GitVersion.MsBuild
dotnet add package System.CommandLine
dotnet add package Sdcb.PaddleOCR
dotnet add package Sdcb.PaddleOCR.Models.Local
dotnet add package Sentry.Profiling
dotnet add package Serilog.Extensions.Logging
dotnet add package Serilog.Settings.Configuration
dotnet add package Serilog.Sinks.Async
dotnet add package Serilog.Sinks.Console
dotnet add package Serilog.Sinks.File
dotnet add package Serilog.Sinks.InMemory
dotnet add package SixLabors.ImageSharp
dotnet add package NeoSolve.ImageSharp.AVIF
dotnet add package SixLabors.ImageSharp.Drawing
dotnet add package Tmds.DBus.Protocol
dotnet add package Xdg.Directories
dotnet add package ZXing.Net.Bindings.ImageSharp.V3
dotnet add package BrycensRanch.MegaApiClient
dotnet add package SSH.NET
dotnet add package Sdcb.OpenCvSharp4.mini.runtime.ubuntu.24.04-x64 --version 4.11.0.34
dotnet add package Sdcb.OpenCvSharp4.mini.runtime.ubuntu.24.04-arm64 --version 4.11.0.34
dotnet add package Sdcb.PaddleInference.runtime.linux-x64.openblas
dotnet add package Sdcb.PaddleInference.runtime.linux-arm64
dotnet add package runtime.any.System.Resources.ResourceManager
dotnet add package runtime.any.System.Runtime
dotnet add package runtime.any.System.Reflection
dotnet add package runtime.any.System.Runtime.InteropServices
dotnet add package runtime.any.System.Reflection.Extensions
dotnet add package runtime.any.System.IO
dotnet add package runtime.any.System.Reflection.Primitives
dotnet add package runtime.any.System.Globalization
dotnet add package runtime.any.System.Runtime.Handles
dotnet add package runtime.any.System.Threading.Tasks
dotnet add package runtime.any.System.Text.Encoding
dotnet add package Dapper
dotnet add package Microsoft.Extensions.Configuration.EnvironmentVariables
dotnet add package Dapper.AOT
dotnet add package Microsoft.Extensions.Configuration.Json
dotnet add package JsonPath.Net
dotnet add package FluentFTP
dotnet add package Microsoft.AspNet.WebApi.Client
dotnet add package Microsoft.Data.Sqlite
dotnet add package SQLitePCLRaw.bundle_e_sqlite3
dotnet add package SQLitePCLRaw.provider.sqlite3
dotnet add package runtime.unix.System.Private.Uri
dotnet add package Microsoft.Extensions.Configuration.CommandLine
dotnet add package MimeTypes
dotnet add package Avalonia.Markup.Xaml.Loader
dotnet add package FluentAvaloniaUI
dotnet add package FluentIcons.Avalonia.Fluent
dotnet add package CommunityToolkit.Mvvm
dotnet add package HarfBuzzSharp
dotnet add package HarfBuzzSharp.NativeAssets.Linux
dotnet add package HarfBuzzSharp.NativeAssets.macOS
dotnet add package HarfBuzzSharp.NativeAssets.Win32
dotnet add package HarfBuzzSharp.NativeAssets.WebAssembly
dotnet add package Markdown.Avalonia
dotnet add package SkiaSharp
dotnet add package SkiaSharp.NativeAssets.Linux
dotnet add package SkiaSharp.NativeAssets.macOS
dotnet add package SkiaSharp.NativeAssets.Win32
dotnet add package SkiaSharp.NativeAssets.WebAssembly
dotnet add package CasCap.Api.GooglePhotos
dotnet add package BrycensRanch.Aptabase.Core
dotnet add package AsyncImageLoader.Avalonia
dotnet add package Avalonia.Desktop
dotnet add package runtime.any.System.Collections
dotnet add package runtime.unix.System.Diagnostics.Debug
dotnet add package Avalonia.Diagnostics
